#
# AppSwitch docker-compose file.
#
# daemon service:
#  docker-compose up -d appswitch
#
# test service:
#  docker-compose up -d test
#  ax run -- curl -I test:8000

version: '2.3'

volumes:
  appswitch_logs:

services:
  appswitch:
    image: appswitch/ax
    pid: "host"
    network_mode: "host"
    privileged: true
    volumes:
      - /usr/bin:/usr/bin
      - /var/run/appswitch:/var/run/appswitch
      - appswitch_logs:/var/log
    env_file:
      - ${AX_CONFIG_FILE:-ax.config}

  test:
    image: python:alpine
    entrypoint: /usr/bin/ax run --name test
    command: python -m http.server
    privileged: true
    networks: []
    volumes:
      - /usr/bin:/usr/bin
      - /var/run/appswitch:/var/run/appswitch
    depends_on:
      - appswitch
