# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.1"

#
# AppSwitch single-node cluster example.
#

$script = <<-SCRIPT

yum check-update
yum install -y iperf3 net-tools nmap-ncat

# Install docker
#
curl -fsSL https://get.docker.com/ | sh
systemctl enable docker
systemctl start docker
usermod -aG docker vagrant

# Install docker-compose
#
curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "CentosBox/Centos7-v7.3-Minimal"

  config.vm.synced_folder ".", "/home/vagrant/appswitch"

  config.vm.provision "shell", inline: $script, privileged: true

  config.ssh.pty = true
  config.ssh.insert_key = false

  name = "host"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = name
  end

  config.vm.define "default", primary: true do |node|
    node.vm.hostname = name

  end
end


