# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.1"

#
# AppSwitch multi-node cluster example.
#

$script = <<-SCRIPT

yum check-update
yum install -y iperf3 net-tools nmap-ncat

# Install docker
#
curl -fsSL https://get.docker.com/ | sh
systemctl enable docker
systemctl start docker
usermod -aG docker vagrant

# Install docker-compose
#
curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# Stop and disable firewall
#
systemctl stop firewalld
systemctl disable firewalld

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "CentosBox/Centos7-v7.3-Minimal"

  config.vm.synced_folder ".", "/home/vagrant/appswitch"

  config.vm.provision "shell", inline: $script, privileged: true

  config.ssh.pty = true
  config.ssh.insert_key = false

  num_nodes = 2
  num_nodes.times do |n|
    name = "host#{n}"
    ip = "192.168.56.#{n+10}"
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip, virtualbox__intnet: true
      node.vm.provider "virtualbox" do |vb|
        vb.name = "ax_" + name
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
  end
end


